### ISSUE TITLE
`1b-upsertCases.js` job failing with TypeError

### ISSUE THREAD

**Issue by jayesse** [OpenFn/unicef-thailand#64]
## Describe the bug
This bug is related to issue OpenFn/language-primero#33 where the `1b-upsertCases.js` job was updated to load PLH and Risk Data to Primero.

When this job runs, we get the following error for certain people (not all CIDs):

```
╭─────────────────────────────────────────────╮
│ ◲ ◱  @openfn/core#v1.4.8 (Node.js v18.10.0) │
│ ◳ ◰          @openfn/language-primero@2.2.8 │
╰─────────────────────────────────────────────╯
TypeError [Error]: Cannot read properties of undefined (reading 'id')
    at vm.js:3125:49
    at Array.map (<anonymous>)
    at magicallyBuildMappingForRiskModel (vm.js:3115:12)
    at vm.js:3251:35
    at VM2 Wrapper.apply (/home/app/assets/node_modules/vm2/lib/bridge.js:485:11)
    at /home/app/priv/language_packs/language-primero-v2.2.8/node_modules/@openfn/language-common/lib/Adaptor.js:95:12
    at /home/app/priv/language_packs/language-primero-v2.2.8/node_modules/@openfn/language-common/lib/Adaptor.js:314:16
    at Array.reduce (<anonymous>)
```

## To Reproduce
1. Here is a link to a [failed run](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06348f0e-2d73-700b-bdd7-f7be95d775b0) on OpenFn.org which is indicative of the bug

### expression.js
*Please make changes in the `staging` branch!* ⚠️
Link to the job itself in Github: https://github.com/OpenFn/primero-thailand/blob/staging/jobs/1b-upsertCases.js

### state.json
This is step 2 job in a flow. 
1. Run job1 `/staging/jobs/1-getPatientData.js` to generate state for job 2. 
- state.configuration: `MOPH Thailand HIS API - DEMO Alpha (Unicef)`
- state.data: Use this Message sent by the Primero webhook for `"national_id_no": "1419903179965"`
https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/06348f0d-c655-745f-915d-2115431c38e7
2.  Use the final state of the first job to run the 2nd job
- `state.configuration`: see LP `Primero Thailand Demo API User (Open Function)` (Note... this user is for **basic auth**.)

## Expected behavior
We expect the job to run successfully without any errors. This should result in PLH and Risk Model form in Primero being filled, with the "Last sync" date properly indicated in the Primero UI.

## To test/resolve
1. After the desired output is working locally, please push commits to `staging`.
2. I will then re-run [this job run](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/06348f0d-cf3a-795d-bd98-71e63b399c13) to re-trigger the flow on platform. 

## Toggl 
UNICEF Thailand

**Comment by aleksa-krolls** [comment]
@mtuchi can you please prioritize this today?

**Comment by aleksa-krolls** [comment]
@mtuchi I just re-tested this scenario by clicking "play" on [this run](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/runs/0634d09e-5bb1-7de2-998d-cbfb9c082610) to retry the flow describe above... this passes! 

However, I also re-tested with a couple of other records and see this errors in one `1b-upsertCases.js` job run: 
- [See job 2 run failure](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/0633af02-fa1c-77f1-86c4-3cd6f50dfe36) with error `TypeError: Cannot read properties of undefined (reading 'services_section')`. 
- You can replicate this error by using [this Message](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/0633af02-fa1c-77f1-86c4-3cd6f50dfe36) as `state.data` for the job 1 `1-getPatientData.js` step in order to generate state for job 2

**Comment by mtuchi** [comment]
I couldn't reproduce the error, I am getting this error instead 
```
Error: Server responded with:
{
  "statusCode": 422,
  "body": {
    "errors": [
      {
        "status": 422,
        "resource": "/api/v2/cases/3b9b999f-4b1a-47b6-8f94-871e23b23815",
        "detail": [
          "/cid",
          "/id",
          "/hn",
          "/pname",
          "/fname",
          "/lname",
          "/occupation_name",
          "/citizenship_name",
          "/nationality",
          "/nationality_name",
          "/birthday",
          "/birthtime",
          "/deathday",
          "/hid",
          "/addrpart",
          "/moopart",
          "/tmbpart",
          "/amppart",
          "/chwpart",
          "/hometel",
          "/informtel",
          "/informaddr",
          "/marrystatus",
          "/marrystatus_name",
          "/pttype",
          "/pttype_name",
          "/pcode",
          "/pcode_name",
          "/religion",
          "/religion_name",
          "/sex_name",
          "/educate",
          "/education_name",
          "/passport_no",
          "/height",
          "/hcode",
          "/hname",
          "/anc",
          "/ipt",
          "/interventions"
        ],
        "message": "Invalid Record JSON"
      }
    ]
  },
```
#### Environment 
```
╭─────────────────────────────────────────────╮
│ ◲ ◱  @openfn/core#v1.4.8 (Node.js v18.10.0) │
│ ◳ ◰          @openfn/language-primero@2.8.0 │
╰─────────────────────────────────────────────╯
```
cc @aleksa-krolls @jayesse

**Comment by aleksa-krolls** [comment]
@mtuchi Tomorrow can you share with me on Slack what is the output we are sending to Primero in this job? 

Per the error message you shared, it looks like we are unnecessarily sending extra fields to Primero... these fields below, for example, look like Child Shield (source) fields and not Primero (destination) fields. 
```
          "/cid",
          "/id",
          "/hn",
          "/pname",
          "/fname",
          "/lname",
          "/occupation_name",

**Comment by mtuchi** [comment]
> @mtuchi Tomorrow can you share with me on Slack what is the output we are sending to Primero in this job?
> 
> Per the error message you shared, it looks like we are unnecessarily sending extra fields to Primero... these fields below, for example, look like Child Shield (source) fields and not Primero (destination) fields.
> 
> ```
>           "/cid",
>           "/id",
>           "/hn",
>           "/pname",
>           "/fname",
>           "/lname",
>           "/occupation_name",
> ```

@aleksa-krolls fix this error #71 , now I am getting this error 
```
 "errors": [
      {
        "status": 422,
        "resource": "/api/v2/cases/3b9b999f-4b1a-47b6-8f94-871e23b23815",
        "detail": [
          "/record_id"
        ],
        "message": "Invalid Record JSON"
      }
    ]
```

**Comment by aleksa-krolls** [comment]
@jayesse this is ready for your testing, although we have a temporary fix in place (see my comments below). But let us know if anything else pops up. 

@mtuchi I have (1) the adaptor issue workaround and (2) change to how we send record `id` ([see my Slack comment](https://openfn.slack.com/archives/C03EQQB5W7R/p1666109751605109?thread_ts=1666105132.467079&cid=C03EQQB5W7R)) implemented on `staging`. The job is now working for cids [1419903179965](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/06348f0d-c655-745f-915d-2115431c38e7) and [1400800050937](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/messages/0633af02-fa1c-77f1-86c4-3cd6f50dfe36). 


See [this issue](https://github.com/OpenFn/adaptors/issues/30) I logged on `language-primero`. Once a new adaptor version is released, please revisit this `1b-upsertCases.js` job to make the appropriate changes so that it will work with that new adaptor version. 
**Once working locally, please submit a PR to staging, but do not merge yet.** (The client will be actively testing tomorrow, so I don't want to deploy to staging until I've tested it myself.)

**Comment by mtuchi** [comment]
@aleksa-krolls I released the new adaptor version for `language-primero` `v2.9.0` and update `1b-upsertCases.js` to use the latest version of `language-primero`. See #71

**Comment by aleksa-krolls** [comment]
@mtuchi I merged #71 to `staging` and updated the [platform job](https://www.openfn.org/projects/primero-thailand-io-unicef---staging/jobs/jyzqmq) to use `v2.9.0`. So far tests are passing 😊

@jayesse tomorrow can you please test as well? It would be good to run full the test suite now for this Flow 2, and make sure that the existing Jobs 3 and 4 in this flow still behave as expected. If you're not sure the best way to test these, let's chat tomorrow! 
<img width="1243" alt="Screen Shot 2022-10-19 at 7 30 49 PM" src="https://user-images.githubusercontent.com/16758106/196750674-0f95f0c5-1711-48cc-971e-0a26ad83cdf9.png">

**Comment by jayesse** [comment]
Thanks @aleksa-krolls I'd give it a go today, and then we can chat tomorrow. Cheers.

**Comment by aleksa-krolls** [comment]
@jayesse can we close this one out? :)
